//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaDiaperSkill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlexaRequest
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public string ApplicationId { get; set; }
        public string RequestId { get; set; }
        public string Intent { get; set; }
    }
}
