//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaDiaperSkill.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JoshRKulpEntities : DbContext
    {
        public JoshRKulpEntities()
            : base("name=JoshRKulpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Diaper> Diapers { get; set; }
        public DbSet<Kid> Kids { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
