//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaDiaperSkill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diaper
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Count { get; set; }
        public int KidId { get; set; }
    
        public virtual Kid Kid { get; set; }
    }
}
