//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaDiaperSkill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Kids = new HashSet<Kid>();
        }
    
        public int Id { get; set; }
        public string AmazonId { get; set; }
    
        public virtual ICollection<Kid> Kids { get; set; }
    }
}
